version: "3"

services:
  trust-anchor.org:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./examples-docker/federation_authority:/django-project
    networks:
      - oidcfed
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example.json &&
        python3 manage.py runserver 0.0.0.0:8000"

  cie-provider.org:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8002
    ports:
      - "8002:8002"
    volumes:
      - ./examples-docker/provider:/django-project
    networks:
      - oidcfed
    depends_on:
      - trust-anchor.org
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example.json &&
        python3 manage.py runserver 0.0.0.0:8002"

  relying-party.org:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8001
    ports:
      - "8001:8001"
    volumes:
      - ./examples-docker/relying_party:/django-project
    networks:
      - oidcfed
    depends_on:
      - trust-anchor.org
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example.json &&
        python3 manage.py runserver 0.0.0.0:8001"

networks:
  oidcfed:
